export const invalidBody = (key: string) => `${key} tidak valid`;
export const incompleteKey = (key: string, placement: string) => `Missing required key in ${placement}: ${key}`;
export const incompleteValue = (key: string, placement: string) => `Missing required value in ${placement}: ${key}`;
export const invalidEmailOrPassword = () => 'Email atau kata sandi salah';
export const invalidType = (key: string) => `Value is invalid data type: ${key}`;
export const invalidFileType = (key: string, message: string) => `Value of ${key} must be in format: ${message}`;
export const maxFileSize = (key: string) => `File ${key} melebihi ukuran`;
export const notFoundResource = (key: string) => `Tidak ditemukan: ${key}`;
export const errorFindResource = (key?: string) => `Failed find resource: ${key}`;
export const errorCreateResource = (key: string) => `Failed create resource: ${key}`;
export const errorUpdateResource = (key: string) => `Failed update resource: ${key}`;
export const errorDeleteResource = (key: string) => `Failed delete resource: ${key}`;
export const invalidFormat = (key: string) => `Format tidak valid: ${key}`;
export const alreadyUsed = (key: string) => `Isian sudah digunakan: ${key}`;
export const duplicate = (key: string) => `${key}`;
export const invalidOption = (key: string) => `Isian diluar opsi: ${key}`;
export const loginError = () => 'Gagal masuk';
export const unauthorized = () => 'Failed to authorized';
export const forbidden = () => 'Forbiden access';
export const generalRequestErrors = (key: string) => `${key}`;
export const somethingWentWrong = 'Terjadi kesalahan padam server';
